/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui;

import Controller.ConnectDB;
import Controller.HoaDonData;
import Controller.NhanVienData;
import Model.HoaDon;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hc
 */
public class ThongKeBaoCaoFrm extends javax.swing.JPanel {
    private ConnectDB connectDB;
    private HoaDonData hoaDonData;
    private NhanVienData nhanVienData;
    /**
     * Creates new form ThongKeBaoCaoFrm
     */
    public ThongKeBaoCaoFrm() {
        initComponents();
        connectDB = new ConnectDB();
        hoaDonData = new HoaDonData(connectDB.getConnection());
        nhanVienData = new NhanVienData(connectDB.getConnection());
        
    }
    
    private void loadDataToTable() {
        Vector<Vector<Object>> data = hoaDonData.getHoaDonData();
        Vector<String> columnNames = hoaDonData.getColumnNames();
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        table_HoaDon.setModel(model);
    }
    // Khai báo phương thức updateTableHoaDon
    private void updateTableHoaDon(Vector<HoaDon> danhSachHoaDon) {
    DefaultTableModel model = (DefaultTableModel) table_HoaDon.getModel();
    model.setRowCount(0); // Xóa tất cả các dòng hiện có trong bảng

    for (HoaDon hoaDon : danhSachHoaDon) {
        // Thêm từng hóa đơn vào bảng
        model.addRow(new Object[]{
            hoaDon.getMaHD(),
            hoaDon.getMaNV(),
            hoaDon.getNgayLap(),
            hoaDon.getTongTien()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_HoaDon = new javax.swing.JTable();
        btnLichSuGiaoDich = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTongDoanhThu = new javax.swing.JLabel();
        cbTheoThang = new javax.swing.JComboBox<>();
        btnTongDoanhThu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTongLuongNhanVien = new javax.swing.JLabel();
        btnTongLuongNhanVien = new javax.swing.JButton();
        txtMaHoaDon = new javax.swing.JTextField();
        btnTimHoaDon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnInBaoCao = new javax.swing.JButton();

        table_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Tên Nhân Viên", "Ngày Lập", "Tổng Tiền"
            }
        ));
        jScrollPane1.setViewportView(table_HoaDon);

        btnLichSuGiaoDich.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLichSuGiaoDich.setText("Lịch Sử Giao Dịch");
        btnLichSuGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLichSuGiaoDichMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Thống Kê Doanh Thu ");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng Doanh Thu Tháng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tổng Tiền");

        txtTongDoanhThu.setForeground(new java.awt.Color(0, 51, 51));
        txtTongDoanhThu.setText("0,00Đ");

        cbTheoThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbTheoThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTheoThangActionPerformed(evt);
            }
        });

        btnTongDoanhThu.setBackground(new java.awt.Color(153, 153, 255));
        btnTongDoanhThu.setText("Tổng doanh thu");
        btnTongDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTongDoanhThuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongDoanhThu)))
                .addGap(18, 18, 18)
                .addComponent(cbTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTongDoanhThu)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTongDoanhThu))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTongDoanhThu))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("THỐNG KÊ LƯƠNG NHÂN VIÊN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tổng Tiền Lương Của Nhân Viên");

        txtTongLuongNhanVien.setText("0,00Đ");

        btnTongLuongNhanVien.setBackground(new java.awt.Color(153, 153, 255));
        btnTongLuongNhanVien.setText("Tổng Tiền Lương ");
        btnTongLuongNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTongLuongNhanVienMouseClicked(evt);
            }
        });
        btnTongLuongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongLuongNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addComponent(txtTongLuongNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTongLuongNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(549, 549, 549)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTongLuongNhanVien)
                    .addComponent(btnTongLuongNhanVien))
                .addGap(19, 19, 19))
        );

        btnTimHoaDon.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnTimHoaDon.setText("Tìm Kiếm");
        btnTimHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimHoaDonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Tra Cứu Lịch Sử Giao Dịch");

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-30.png"))); // NOI18N
        btnXoa.setText("Xóa Lịch Sử Giao Dịch");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnInBaoCao.setBackground(new java.awt.Color(153, 153, 255));
        btnInBaoCao.setText("IN BÁO CÁO");
        btnInBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBaoCaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLichSuGiaoDich)
                .addGap(257, 257, 257)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnTimHoaDon)
                .addGap(80, 80, 80)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimHoaDon)
                        .addComponent(btnInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLichSuGiaoDich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTongDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTongDoanhThuMouseClicked
   int selectedMonth = Integer.parseInt(cbTheoThang.getSelectedItem().toString());
    
    // Assuming you have a method tinhTongTienTheoThang(year, month) to calculate the total revenue
    // You can call this method to get the total revenue for the selected month
    int year = 2023; // You can replace this with the desired year
    float totalRevenue = hoaDonData.tinhTongTienTheoThang(year, selectedMonth);
    
    if (totalRevenue != 0.0f) {
        // Display a message dialog with the calculated total revenue
        
        JOptionPane.showMessageDialog(this, String.format("Tổng doanh thu tháng %d: %.3fĐ", selectedMonth, totalRevenue), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        txtTongDoanhThu.setText(String.format("%.3fĐ", totalRevenue));
    } else {
        // Display a message dialog indicating that there is no data
        JOptionPane.showMessageDialog(this, "Không có dữ liệu cho tháng này.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnTongDoanhThuMouseClicked

    private void btnLichSuGiaoDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLichSuGiaoDichMouseClicked
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_btnLichSuGiaoDichMouseClicked

    private void btnTongLuongNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTongLuongNhanVienMouseClicked
        // TODO add your handling code here:NhanVienData nhanVienData = new NhanVienData(connection);
    // Sử dụng đối tượng NhanVienData để tính tổng tiền lương của nhân viên
    float tongLuong = nhanVienData.tinhTongLuongNhanVien();
    
    // Hiển thị tổng tiền lương lên trên giao diện
    txtTongLuongNhanVien.setText(String.format("%.3fĐ", tongLuong));
    
    // Hiển thị hộp thoại thông báo
    JOptionPane.showMessageDialog(this, String.format("Tổng tiền lương của nhân viên: %.2fĐ", tongLuong), "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnTongLuongNhanVienMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
     // Hiển thị hộp thoại xác nhận
int confirmed = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa lịch sử giao dịch?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
int maHD = Integer.parseInt(txtMaHoaDon.getText());
// Kiểm tra người dùng đã chọn "Yes" hay "No"
if (confirmed == JOptionPane.YES_OPTION) {
    // Người dùng chọn "Yes", tiến hành xóa
    boolean result = hoaDonData.deleteHoaDon(maHD);

    if (result) {
        JOptionPane.showMessageDialog(this, "Xóa lịch sử giao dịch thành công");
        // Sau khi xóa xong, có thể làm mới bảng hoặc cập nhật bảng
        // refreshTable();
        loadDataToTable();
    } else {
        JOptionPane.showMessageDialog(this, "Xóa lịch sử thất bại");
    }
} else {
    // Người dùng chọn "No", không thực hiện xóa
    JOptionPane.showMessageDialog(this, "Đã hủy xóa lịch sử giao dịch");
}
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnTimHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimHoaDonMouseClicked
     int maHoaDon = Integer.parseInt(txtMaHoaDon.getText());
    
    // Gọi phương thức tìm kiếm hóa đơn theo mã
    Vector<HoaDon> danhSachHoaDon = hoaDonData.searchHoaDonByMaHoaDon(maHoaDon);
    
    // Kiểm tra xem có kết quả tìm kiếm hay không
    if (!danhSachHoaDon.isEmpty()) {
        // Cập nhật bảng table_HoaDon với danh sách hóa đơn tìm kiếm
       updateTableHoaDon(danhSachHoaDon);
    } else {
        // Hiển thị thông báo nếu không tìm thấy hóa đơn
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn có mã " + maHoaDon,
                "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTimHoaDonMouseClicked

    private void btnTongLuongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongLuongNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTongLuongNhanVienActionPerformed

    private void cbTheoThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTheoThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTheoThangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnInBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBaoCaoActionPerformed
        // TODO add your handling code here:
    int selectedMonth = Integer.parseInt(cbTheoThang.getSelectedItem().toString());
    int year = 2023; // Thay đổi năm theo nhu cầu của bạn
    float doanhThuThang = hoaDonData.tinhTongTienTheoThang(year, selectedMonth);
    float luongNhanVien = nhanVienData.tinhTongLuongNhanVien();

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Chọn nơi lưu trữ báo cáo Excel");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int option = fileChooser.showSaveDialog(this);

    if (option == JFileChooser.APPROVE_OPTION) {
        String filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if (!filePath.endsWith(".xlsx")) {
            filePath += ".xlsx";
        }
        hoaDonData.exportToExcel(filePath, doanhThuThang, luongNhanVien,(DefaultTableModel) table_HoaDon.getModel());

        JOptionPane.showMessageDialog(this, "Báo cáo đã được xuất ra file Excel!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        
    
    }//GEN-LAST:event_btnInBaoCaoActionPerformed

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBaoCao;
    private javax.swing.JButton btnLichSuGiaoDich;
    private javax.swing.JButton btnTimHoaDon;
    private javax.swing.JButton btnTongDoanhThu;
    private javax.swing.JButton btnTongLuongNhanVien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTheoThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_HoaDon;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JLabel txtTongDoanhThu;
    private javax.swing.JLabel txtTongLuongNhanVien;
    // End of variables declaration//GEN-END:variables

    
}
