/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hc
 */
public class TrangChuForm extends javax.swing.JFrame {
private JPanel childPanel;
    /**
     * Creates new form Home
     */
    public TrangChuForm() {
        initComponents();
        setLocationRelativeTo(null);
         Panel_body.removeAll();
        childPanel =new Home();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_body = new javax.swing.JPanel();
        mnMENUTOP = new javax.swing.JMenuBar();
        MenuItem_NhaCungCap = new javax.swing.JMenu();
        MenuItem_Home = new javax.swing.JMenuItem();
        MenuItem_BanHang = new javax.swing.JMenuItem();
        MenuItem_SanPham = new javax.swing.JMenuItem();
        MenuItem_NhanVien = new javax.swing.JMenuItem();
        MenuItem_NhaCC = new javax.swing.JMenuItem();
        MenuItem_ThongKe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItem_Thoat = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuItem_HoTro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Bán Bánh Kẹo");

        Panel_body.setLayout(new java.awt.CardLayout());

        MenuItem_NhaCungCap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MenuItem_NhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-30.png"))); // NOI18N
        MenuItem_NhaCungCap.setText(" Manager                      ");
        MenuItem_NhaCungCap.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MenuItem_NhaCungCapItemStateChanged(evt);
            }
        });
        MenuItem_NhaCungCap.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MenuItem_NhaCungCapStateChanged(evt);
            }
        });
        MenuItem_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuItem_NhaCungCapMouseEntered(evt);
            }
        });
        MenuItem_NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_NhaCungCapActionPerformed(evt);
            }
        });

        MenuItem_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-24.png"))); // NOI18N
        MenuItem_Home.setText("Home");
        MenuItem_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_HomeActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_Home);

        MenuItem_BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-buy-24.png"))); // NOI18N
        MenuItem_BanHang.setText("Bán Hàng");
        MenuItem_BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_BanHangActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_BanHang);

        MenuItem_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cake-24.png"))); // NOI18N
        MenuItem_SanPham.setText("Sản Phẩm");
        MenuItem_SanPham.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                MenuItem_SanPhamAncestorRemoved(evt);
            }
        });
        MenuItem_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_SanPhamMouseClicked(evt);
            }
        });
        MenuItem_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_SanPhamActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_SanPham);

        MenuItem_NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-staff-24.png"))); // NOI18N
        MenuItem_NhanVien.setText("Nhân Viên");
        MenuItem_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_NhanVienMouseClicked(evt);
            }
        });
        MenuItem_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_NhanVienActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_NhanVien);

        MenuItem_NhaCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-supplier-24.png"))); // NOI18N
        MenuItem_NhaCC.setText("Nhà Cung Cấp");
        MenuItem_NhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_NhaCCActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_NhaCC);

        MenuItem_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-report-24.png"))); // NOI18N
        MenuItem_ThongKe.setText("Thống Kê ");
        MenuItem_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ThongKeActionPerformed(evt);
            }
        });
        MenuItem_NhaCungCap.add(MenuItem_ThongKe);

        mnMENUTOP.add(MenuItem_NhaCungCap);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-setting-30.png"))); // NOI18N
        jMenu2.setText("  Setting                       ");

        MenuItem_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-login-24.png"))); // NOI18N
        MenuItem_Thoat.setText("Exit");
        MenuItem_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuItem_ThoatMouseExited(evt);
            }
        });
        MenuItem_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ThoatActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_Thoat);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-access-24.png"))); // NOI18N
        jMenuItem2.setText("Đăng Xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        MenuItem_HoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-help-24.png"))); // NOI18N
        MenuItem_HoTro.setText("Hỗ Trợ");
        MenuItem_HoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_HoTroActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_HoTro);

        mnMENUTOP.add(jMenu2);

        setJMenuBar(mnMENUTOP);
        mnMENUTOP.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_body, javax.swing.GroupLayout.DEFAULT_SIZE, 1525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_body, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_BanHangActionPerformed
        // TODO add your handling code here:
        childPanel =new BanHangFrm();
        Panel_body.removeAll();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }//GEN-LAST:event_MenuItem_BanHangActionPerformed

    private void MenuItem_SanPhamAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MenuItem_SanPhamAncestorRemoved
        // TODO add your handling code here:// TODO add your handling code here:

    }//GEN-LAST:event_MenuItem_SanPhamAncestorRemoved

    private void MenuItem_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_SanPhamMouseClicked

    }//GEN-LAST:event_MenuItem_SanPhamMouseClicked

    private void MenuItem_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_SanPhamActionPerformed
        // TODO add your handling code here:
        childPanel =new SanPhamFrm();
        Panel_body.removeAll();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }//GEN-LAST:event_MenuItem_SanPhamActionPerformed

    private void MenuItem_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_NhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_NhanVienMouseClicked

    private void MenuItem_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_NhanVienActionPerformed
        // TODO add your handling code here:
        Panel_body.removeAll();
        childPanel =new NhanVienFrm();

        Panel_body.add(childPanel);
        Panel_body.validate();

    }//GEN-LAST:event_MenuItem_NhanVienActionPerformed

    private void MenuItem_NhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_NhaCCActionPerformed
        // TODO add your handling code here:
        Panel_body.removeAll();
        childPanel =new NhaCungCapFrm();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }//GEN-LAST:event_MenuItem_NhaCCActionPerformed

    private void MenuItem_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ThongKeActionPerformed
        // TODO add your handling code here:
        Panel_body.removeAll();
        childPanel =new ThongKeBaoCaoFrm();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }//GEN-LAST:event_MenuItem_ThongKeActionPerformed

    private void MenuItem_NhaCungCapItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MenuItem_NhaCungCapItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuItem_NhaCungCapItemStateChanged

    private void MenuItem_NhaCungCapStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MenuItem_NhaCungCapStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuItem_NhaCungCapStateChanged

    private void MenuItem_NhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_NhaCungCapMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuItem_NhaCungCapMouseEntered

    private void MenuItem_NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_NhaCungCapActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MenuItem_NhaCungCapActionPerformed

    private void MenuItem_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_ThoatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_ThoatMouseExited

    private void MenuItem_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ThoatActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát ứng dụng?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);

        // Kiểm tra lựa chọn của người dùng
        if (result == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn "Yes", thoát ứng dụng
            System.exit(0);
        }

    }//GEN-LAST:event_MenuItem_ThoatActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        LoginFrm runFrm = new LoginFrm();
        runFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuItem_HoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_HoTroActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuItem_HoTroActionPerformed

    private void MenuItem_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_HomeActionPerformed
        // TODO add your handling code here:
        Panel_body.removeAll();
        childPanel =new Home();
        Panel_body.add(childPanel);
        Panel_body.validate();
    }//GEN-LAST:event_MenuItem_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_BanHang;
    private javax.swing.JMenuItem MenuItem_HoTro;
    private javax.swing.JMenuItem MenuItem_Home;
    private javax.swing.JMenuItem MenuItem_NhaCC;
    private javax.swing.JMenu MenuItem_NhaCungCap;
    private javax.swing.JMenuItem MenuItem_NhanVien;
    private javax.swing.JMenuItem MenuItem_SanPham;
    private javax.swing.JMenuItem MenuItem_Thoat;
    private javax.swing.JMenuItem MenuItem_ThongKe;
    private javax.swing.JPanel Panel_body;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mnMENUTOP;
    // End of variables declaration//GEN-END:variables
}
